// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZtmkC1xisv2sJhQ8GoiG_qtsBON9LLw',
    appId: '1:395060331810:web:494bdbc3fc70cb8495d17b',
    messagingSenderId: '395060331810',
    projectId: 'reservation-app-e2cc9',
    authDomain: 'reservation-app-e2cc9.firebaseapp.com',
    storageBucket: 'reservation-app-e2cc9.firebasestorage.app',
    measurementId: 'G-ND86MC1F81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI75bBRwxUg-ANw98FFwxj2uNprwQUWG0',
    appId: '1:395060331810:android:872f2077f456e37695d17b',
    messagingSenderId: '395060331810',
    projectId: 'reservation-app-e2cc9',
    storageBucket: 'reservation-app-e2cc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnaFTCC_TcpknmtfHS6Whtz9tH_1FHUnw',
    appId: '1:395060331810:ios:33f2b7a01b1a33cc95d17b',
    messagingSenderId: '395060331810',
    projectId: 'reservation-app-e2cc9',
    storageBucket: 'reservation-app-e2cc9.firebasestorage.app',
    iosBundleId: 'com.example.reservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnaFTCC_TcpknmtfHS6Whtz9tH_1FHUnw',
    appId: '1:395060331810:ios:33f2b7a01b1a33cc95d17b',
    messagingSenderId: '395060331810',
    projectId: 'reservation-app-e2cc9',
    storageBucket: 'reservation-app-e2cc9.firebasestorage.app',
    iosBundleId: 'com.example.reservationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzZtmkC1xisv2sJhQ8GoiG_qtsBON9LLw',
    appId: '1:395060331810:web:c20cdc5db9888be595d17b',
    messagingSenderId: '395060331810',
    projectId: 'reservation-app-e2cc9',
    authDomain: 'reservation-app-e2cc9.firebaseapp.com',
    storageBucket: 'reservation-app-e2cc9.firebasestorage.app',
    measurementId: 'G-789GVZYBZG',
  );
}
